### ISSUE TITLE
date_and_time isn't working as expected in execute_decision_table

### ISSUE THREAD

**Issue by thaukap** [EdgeVerve/feel#1]
Hi everybody!

We're using js-feel for a week now but struggling in using date_and_time as payload. Here is a simple example code sniped, which should return the result "is greater" because 2018-06-09 is a greater date than 2017-06-08. But it doesn't it always returns "default", means no match.

So what's wrong here:

	it("evaluate js feel with examples for date", function (done) {
		let payload = {
			inputDate: Date.parse("2018-06-09T00:00:00Z")
		};

		let decisionTable = {
			hitPolicy: 'U',
			inputExpressionList: ['inputDate'],
			outputs: ['ComparedDatesResult'],
			inputValuesList:
			['> date_and_time("2017-06-09T00:00:00Z"),< date_and_time("2017-06-09T00:00:00Z"),-'],
			outputValues: [['"is greater"', '"is less"', '"default"']],
			ruleList:
			[
				['> date_and_time("2017-06-09T00:00:00Z")', '"is greater"'],
				['< date_and_time("2017-06-09T00:00:00Z")',	'"is less"'],
				['-', '"default"']
			],
			context: null
		};

		jsFeel.decisionTable.execute_decision_table("test table with date", decisionTable, payload, (err, results) => {
			console.log(results);
			done();
		});
	});

**Comment by SambitKumarPatra** [comment]
Date and time functionalities has not been implemented. Those features will be available in next release(somewhat around end of July, 2017).

**Comment by raghav135** [comment]
+1

**Comment by gustavomick** [comment]
hi!, nice work. have you included date ranges as part of this release?
like [ 2012-12-25...2013-02-14 ]

**Comment by pragyandas** [comment]
@gustavomick Yes absolutely.

**Comment by gustavomick** [comment]
@pragyandas oh thanks, i tried with current version and is not working yet, i think is failing with 3dots token. number range is working thou.

**Comment by pragyandas** [comment]
@gustavomick This is WIP and will be included in the next release 😄

**Comment by pragyandas** [comment]
@gustavomick I have added 'date and time range' feature.  The below expression (comparision expression in DMN FEEL grammar) works now. 
 
``` 
date and time("2017-04-12T11:45:00Z") in [date and time("2017-04-12T11:30:00Z")..date and time("2017-04-12T12:45:00Z")]

``` 

A few things worth mentioning here ;

- date and time in FEEL do not have the notion of milliseconds .
- range is denoted by ".." (2 dots) and "..." (3 dots) is not a valid FEEL grammar token

All the date and time features will be made available as part of  js-feel@1.2.0 release.

**Comment by gustavomick** [comment]
@pragyandas nice thanks. 

regarding ms not working thats odd!

**Comment by pragyandas** [comment]
@gustavomick I completely agree with you on that. The DMN 1.1 documentation doesn't mention anything regarding ms 😞

**Comment by pragyandas** [comment]
date, time, date and time and duration added. Please refer [Date-Time-Support](https://github.com/EdgeVerve/feel/wiki/Date-Time-Support) wiki for more information.
