### ISSUE TITLE
Feature: indicate which rules were used to obtain results

### ISSUE THREAD

**Issue by yanndebonnelmontreal** [EdgeVerve/feel#21]
It could be useful in certain scenarios to be able to receive, when executing decisionTable.execute_decision_table, the rules that were applied to arrive to the result

**Comment by deostroll** [comment]
This is difficult and a known issue. Mainly because of a lot of promises being used. We added logs at critical nodes in our AST, but it turns out that these are quite verbose to follow. You have to get into the habit of debugging this code to understand what is happening.
