### ISSUE TITLE
"now" equivalent ?

### ISSUE THREAD

**Issue by raghav135** [EdgeVerve/feel#3]
Hi, is there a way use today's date / date time in FEEL ?

I guess the actual specification does not support this, is there any workaround that we can use?

Sample use case: we know date of birth in payload.
If age < ... then ...

There are two problems:
The date of birth is a dynamic date field, not a hardcoded string in FEEL
The "now" issue, FEEL expression does not support it

**Comment by pragyandas** [comment]
@raghav135 The support for current date and time has been added to ***feel*** . Please refer to [The Story of Now](https://github.com/EdgeVerve/feel/wiki/Date-Time-Support#the-story-of-now) to understand more about it.

**Comment by raghav135** [comment]
Thanks for example.
